# Generated by Django 5.0.1 on 2024-03-23 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movieapp', '0002_alter_movie_release_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('comments', models.TextField()),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
