# Generated by Django 5.0.1 on 2024-03-23 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movieapp', '0003_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='review',
        ),
    ]
