# Generated by Django 5.0.1 on 2024-03-29 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movieapp', '0003_remove_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='des',
        ),
        migrations.RemoveField(
            model_name='category',
            name='img',
        ),
    ]
