# Generated by Django 5.0.1 on 2024-03-23 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movieapp', '0005_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='content',
            new_name='comments',
        ),
    ]
