# Generated by Django 5.0.1 on 2024-03-23 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movieapp', '0007_alter_movie_release_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='release_date',
            new_name='year',
        ),
    ]
