# Generated by Django 5.0.1 on 2024-03-23 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movieapp', '0009_alter_movie_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='year',
        ),
        migrations.AddField(
            model_name='movie',
            name='release_date',
            field=models.DateField(null=True),
        ),
    ]
