# Generated by Django 5.0.1 on 2024-03-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movieapp', '0011_rename_release_date_movie_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.DateField(default=''),
            preserve_default=False,
        ),
    ]
